### ISSUE TITLE
Problem with KK_PovX

### ISSUE THREAD

**Issue by ghost** [FairBear/KK_PovX#1]
I have a problem with KK_PovX, when I drag and drop bepins into the game directory and when I press the comma button it not doing anything.

**Comment by Llyme** [comment]
The `KK_PovX.dll` file needs to be inside the `BepInEx` folder, so it should be like `Koikatu\BepInEx\KK_PogX.dll`. You'll need to be able to move in school or in an H-scene. The key won't work if you're pressing any other key, you'll have to press the `, (comma)` key only. If it's still not working, it might be that the key isn't set properly in the `Plugin Settings`, which can be found in the settings menu via pressing the `F1` key.

**Comment by FairBear** [comment]
The `KK_PovX.dll` file needs to be inside the `BepInEx` folder, so it should be like `Koikatu\BepInEx\KK_PovX.dll`. You'll need to be able to move in school or in an H-scene. The key won't work if you're pressing any other key, you'll have to press the `, (comma)` key only. If it's still not working, it might be that the key isn't set properly in the `Plugin Settings`, which can be found in the settings menu via pressing the `F1` key. If it still doesn't work, I'll look into it.

**Comment by ghost** [comment]
I try that, it still not working.

**Comment by FairBear** [comment]
Do you have this in your settings?
![image](https://user-images.githubusercontent.com/49444689/81227218-a632ff00-901e-11ea-82cd-704054d0f0e7.png)
This is how it should look like after extracting the folder. You'll need BepInEx installed as well, which can be found ![here](https://github.com/BepInEx/BepInEx/releases).
![image](https://user-images.githubusercontent.com/49444689/81228076-037b8000-9020-11ea-9f56-6e01e90cadd7.png)

**Comment by ghost** [comment]
Yes

**Comment by FairBear** [comment]
Have you tried changing the key to anything other than the comma key? I don't know how to help you any further as I can't think of a possible reason for it to not work. The last thing that could possibly help you is to install the HF Patch made by ManlyMarco as it should give you everything that you need in order to make KK_PovX to work. If the game you're playing is Koikatsu Party, I don't know if the plugin works with it as the game I have is the Japanese version and I have no access to Koikatsu Party. You can download the HF Patch in https://www.patreon.com/posts/36174905.

**Comment by ghost** [comment]
I try that, but it not working.

**Comment by FairBear** [comment]
I apologize but I can't really help you at this point since I don't know whats causing the error. If you do have the `output_log.txt`, it will help me find out what's causing the error. The `output_log.txt` can be found inside the `Koikatu` folder.

**Comment by ghost** [comment]
(https://github.com/FairBear/KK_PovX/files/4589718/LogOutput.log)

**Comment by Terell2018** [comment]
When i put the KK_PovX inside BepinEx or plugins or kk_plugins folder it still show up on plugins settings.

**Comment by FairBear** [comment]
I've uploaded a new update https://github.com/FairBear/KK_PovX/releases/tag/v1.0.1 See if it works.

**Comment by ghost** [comment]
i want to say thank you. it working now.
